version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.9.0
  - dependency-name: "@storybook/addon-controls"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.21
    - 6.2.0
    - 6.2.1
    - 6.2.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: ts-loader
    versions:
    - 9.1.0
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.18
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/vue"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.2.0
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
  - dependency-name: "@storybook/addon-backgrounds"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.20
    - 6.2.0
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.16.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/experimental-utils"
    versions:
    - 4.14.2
    - 4.16.0
    - 4.19.0
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.12
  - dependency-name: chai
    versions:
    - 4.3.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.2
    - 4.16.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: sass
    versions:
    - 1.32.6
